site_name: Wiki programming notes

copyright: Copyright 2020 Simone Di Ricco

repo_url: https://github.com/sdiricco/wiki-programming-notes

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sdiricco


# Extensions
markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.superfences

theme:

  name: material
  
  palette:
    - scheme: slate
  features:
    - navigation.tabs






