site_name: Wiki programming notes

copyright: Copyright 2020 Simone Di Ricco

repo_url: https://github.com/sdiricco/wiki-programming-notes

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sdiricco


# Extensions
markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.superfences

theme:
  name: material
  font:
    text: Open Sans
  # logo: assets/logo.png
  # favicon: images/favicon.png
  
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs







